import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
          <div className="absolute top-0 z-[-2] h-screen w-screen bg-gray-950 bg-[radial-gradient(ellipse_60%_80%_at_50%_-20%,rgba(135,206,220,0.3),rgba(255,255,255,0))]"></div>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
